# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nubank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'SwiftGen', '~> 6.0'

  # Pods for Nubank

  target 'NubankTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
